version: '3'

services:
  ROP-ssr:
    image: ${IMAGE_TAG}-${CI_COMMIT_SHA}
    networks:
      - traefik_net
      - default
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager
      labels:
        - "traefik.tags=http"
        - "traefik.port=80"
        - "traefik.protocol=http"
        - "traefik.docker.network=traefik_net"
        - "traefik.backend=ROP-ssr"
        - "traefik.frontend.rule=Host:ssr.rop.zjuqsc.com"
networks:
  traefik_net:
    external: true